{% set name = "pygmtools" %}
{% set version = "0.5.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygmtools-{{ version }}.tar.gz
  sha256: 85c1ef7d65c41b75788a38822bebdc81649d71b074e42dd2ae4bab898679dbee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.25.1
    - scipy >=1.4.1
    - pillow >=7.2.0
    - numpy >=1.18.5
    - easydict >=1.7
    - appdirs >=1.4.4
    - tqdm >=4.64.1
    - async-timeout
    - aiohttp
    - networkx >=2.8.8

test:
  imports:
    - pygmtools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pygmtools.readthedocs.io/
  summary: pygmtools provides graph matching solvers in Python API and supports numpy and pytorch backends. pygmtools also provides dataset API for standard graph matching benchmarks.
  license: MulanPSL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
